_admin_communication_notification:
    resource: "@AdminCommunicationBundle/Controller/NotificationController.php"
    type: annotation
    prefix: /admin/communication/notification

_admin_communication_message:
    resource: "@AdminCommunicationBundle/Controller/MessageController.php"
    type: annotation
    prefix: /admin/communication/message

