_user_communication_notification:
    resource: "@UserCommunicationBundle/Controller/NotificationController.php"
    type: annotation
    prefix: /user/communication/notification

_user_communication_message:
    resource: "@UserCommunicationBundle/Controller/MessageController.php"
    type: annotation
    prefix: /user/communication/message

