Admin_Notice_Message:
    resource: "@AdminNoticeBundle/Controller/MessageController.php"
    type: annotation
    prefix: /admin/notice/message

Admin_Notice_News:
    resource: "@AdminNoticeBundle/Controller/NewsController.php"
    type: annotation
    prefix: /admin/notice/news

Admin_Notice_Notification:
    resource: "@AdminNoticeBundle/Controller/NotificationController.php"
    type: annotation
    prefix: /admin/notice/notification

