_admin_general_repository:
    resource: "@AdminGeneralBundle/Controller/RepositoryController.php"
    type: annotation
    prefix: /admin/general/repository

_admin_general_media:
    resource: "@AdminGeneralBundle/Controller/MediaController.php"
    type: annotation
    prefix: /admin/general/media

