Admin_General_Repository:
    resource: "@AdminGeneralBundle/Controller/RepositoryController.php"
    type: annotation
    prefix: /admin/general/repository

Admin_General_Media:
    resource: "@AdminGeneralBundle/Controller/MediaController.php"
    type: annotation
    prefix: /admin/general/media

