<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $search
     * @param $page
     * @param $count
     * @param $order_by
     * @param $sort
     * @param $filters
     * @return Paginator
     */
    public function filter($search, $page, $count, $order_by, $sort, $filters)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('m')
            ->from('AppBundle:Message', 'm')
            ->join('m.sender', 'sender')
            ->join('m.receiver', 'receiver')
        ;

        if(!empty($search)) {

            $search = explode(' ', $search);
            foreach ($search as $q) {
                $qb->andWhere($qb->expr()->like('CONCAT(' . implode(", ' ', ", [
                        'm.title',
                        'm.message'
                    ]) . ')', $qb->expr()->literal('%' . $q . '%')));
            }
        }

        if(isset($filters['sender'])) {

            $qb
                ->andWhere('sender.id = :sender')
                ->setParameter('sender', $filters['sender'])
            ;
        }

        if(isset($filters['receiver'])) {

            $qb
                ->andWhere('receiver.id = :receiver')
                ->setParameter('receiver', $filters['receiver'])
            ;
        }

        if(!empty($order_by)) {
            if(in_array($order_by, ['sender', 'receiver'])){
                $qb->orderBy("{$order_by}.fullname", $sort);
            } else {
                $qb->orderBy("m.{$order_by}", $sort);
            }
        }

        $qb
            ->setFirstResult($page * $count)
            ->setMaxResults($count)
        ;

        return new Paginator($qb->getQuery());
    }

    /**
     * @param $ids
     */
    public function bulkDelete($ids)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->delete('AppBundle:Message', 'm')
            ->where($qb->expr()->in('m.id', $ids))
            ->getQuery()
            ->execute()
        ;
    }
}