<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $search
     * @param $page
     * @param $count
     * @param $order_by
     * @param $sort
     * @param $filters
     * @return Paginator
     */
    public function filter($search, $page, $count, $order_by, $sort, $filters)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('n')
            ->from('AppBundle:Notification', 'n')
            ->join('n.receiver', 'receiver')
        ;

        if(!empty($search)) {

            $search = explode(' ', $search);
            foreach ($search as $q) {
                $qb->andWhere($qb->expr()->like('n.notification', $qb->expr()->literal('%' . $q . '%')));
            }
        }

        if(isset($filters['receiver'])) {

            $qb
                ->andWhere('receiver.id = :receiver')
                ->setParameter('receiver', $filters['receiver'])
            ;
        }

        if(isset($filters['statusSee'])) {

            $qb
                ->andWhere('n.statusSee = :statusSee')
                ->setParameter('statusSee', $filters['statusSee'])
            ;
        }

        if(!empty($order_by)) {
            if(in_array($order_by, ['receiver'])){
                $qb->orderBy("{$order_by}.fullname", $sort);
            } else {
                $qb->orderBy("n.{$order_by}", $sort);
            }
        }

        $qb
            ->setFirstResult($page * $count)
            ->setMaxResults($count)
        ;

        return new Paginator($qb->getQuery());
    }

    /**
     * @param $ids
     */
    public function bulkDelete($ids)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->delete('AppBundle:Notification', 'n')
            ->where($qb->expr()->in('n.id', $ids))
            ->getQuery()
            ->execute()
        ;
    }
}
