_user_settings_profile:
	resource:	"@UserSettingsProfileBundle/Controller/"
	prefix:		/user/settings/profile

_admin_users_group:
	resource:	"@AdminUsersGroupBundle/Controller/"
	prefix:		/admin/users/group

