custom:
  resource: routing_custom.yml

AdminUserBundle:
  resource: "@AdminUserBundle/Resources/config/routing.yml"

AdminNoticeBundle:
  resource: "@AdminNoticeBundle/Resources/config/routing.yml"

UserSettingBundle:
  resource: "@UserSettingBundle/Resources/config/routing.yml"

UserNoticeBundle:
  resource: "@UserNoticeBundle/Resources/config/routing.yml"

AdminGeneralBundle:
  resource: "@AdminGeneralBundle/Resources/config/routing.yml"

