_user_settings_profile:
  resource: "@UserSettingsProfileBundle/Controller/"
  type: annotation
  prefix: /user/settings/profile

_admin_users_group:
  resource: "@AdminUsersGroupBundle/Controller/"
  type: annotation
  prefix: /admin/users/group

