src:
  resource: routing_custom.yml

AdminUserBundle:
  resource: "@AdminUserBundle/Resources/config/routing.yml"

AdminCommunicationBundle:
  resource: "@AdminCommunicationBundle/Resources/config/routing.yml"

UserSettingBundle:
  resource: "@UserSettingBundle/Resources/config/routing.yml"

