_admin_users_group:
  resource: "@AdminUsersGroupBundle/Controller/"
  type: annotation
  prefix: /admin/users/group

_admin_users_user:
  resource: "@AdminUsersUserBundle/Controller/"
  type: annotation
  prefix: /admin/users/user

