User_Notice_Message:
    resource: "@UserNoticeBundle/Controller/MessageController.php"
    type: annotation
    prefix: /user/notice/message

User_Notice_Notification:
    resource: "@UserNoticeBundle/Controller/NotificationController.php"
    type: annotation
    prefix: /user/notice/notification

