User_Setting_Password:
    resource: "@UserSettingBundle/Controller/PasswordController.php"
    type: annotation
    prefix: /user/setting/password

User_Setting_Profile:
    resource: "@UserSettingBundle/Controller/ProfileController.php"
    type: annotation
    prefix: /user/setting/profile

