<?php

namespace Admin\News\CategoryBundle\Repository;

/**
 * CatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatRepository extends \Doctrine\ORM\EntityRepository
{
}
