<?php

namespace Admin\Users\GroupBundle\Repository;

use Admin\Users\GroupBundle\Entity\Group;
use Doctrine\ORM\EntityRepository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    /**
     * @param $id
     * @return Group|null
     */
    public function findOneById($id)
    {
        return $this
            ->createQueryBuilder('g')
            ->andWhere('g.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
